# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request_target:
    types: [labeled]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'     
        required: true
      commit:
        description: 'Commit to release'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-install-zip:
    name: "Build Installer"
    runs-on: ubuntu-latest
    if: github.event.release.tag_name
    steps:
      # Checkout target branch for release build
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }} 

      - name: Build txt file
        run: CLIENT=docker RELEASE_VERSION=${{ github.event.release.tag_name }} make build-txt

      - name: Upload txt file
        uses: actions/upload-artifact@v3
        with:
          name: txt-${{ github.event.release.tag_name }}-test
          path: echo-test.txt
          retention-days: 1
  publish-release:
    name: "Publish Release"
    runs-on: ubuntu-latest
    if: github.event.inputs.version && github.event.inputs.commit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "README.md"
          allowUpdates: true
          prerelease: true
          commit: ${{ github.event.inputs.commit }}
          name: ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
